### ISSUE TITLE
0.5.12 No Directive annotation found on NgFileSelect

### ISSUE THREAD

**Issue by qq83387856** [jkuri/ng2-uploader#61] opened 2016-08-16 03:20 UTC
angular rc4

```
import { Component, Input } from "@angular/core";
import { UPLOAD_DIRECTIVES } from "ng2-uploader/ng2-uploader";

@Component({
  selector: 'common-upload',
  template: require('./common-upload.html'),
  directives: [UPLOAD_DIRECTIVES],
})
export class CommonUploadComponent {

  @Input() url: string;

  uploadFile: any;
  options: Object = {
    url: this.url
  };

  handleUpload(data): void {
    if (data && data.response) {
      data = JSON.parse(data.response);
      this.uploadFile = data;
    }
  }
}
```

**Comment by zaneadix** [comment] 2016-08-16 19:44
Just installed and experiencing the same issue.
To paraphrase: +1

**Comment by doncabron** [comment] 2016-08-17 20:38
+1 Same problem here

**Comment by mattathompson** [comment] 2016-08-18 00:09
+1 Same Issue.

**Comment by jkuri** [comment] 2016-08-18 09:41
Hey guys, I bumped the new version (0.5.13), can you try this please? I made an example and cannot reproduce the problem. Thanks.

**Comment by lacroixdavid1** [comment] 2016-08-18 15:46
@jkuri Thx a lot, it's all fixed in 0.5.13 ! Working with Angular 2 rc5, webpack2, all with lastest package dependencies

**Comment by jkuri** [comment] 2016-08-18 20:42
@lacroixdavid1 no problem, good to hear it's working now.

**Closed by jkuri** 2016-08-18 20:42 UTC
